
development:
  adapter: postgresql
  encoding: unicode
  database: website_development
  pool: 5
  username: eifion
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: website_test
  pool: 5
  username: eifion
  password: