development:
  adapter: postgresql
  encoding: unicode
  database: my_website_development
  pool: 5
  username: Drew
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  database: my_website_test
  pool: 5
  username: Drew
  password: pass